# Generated by Django 4.0.4 on 2022-04-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('subject', models.CharField(choices=[('SCI', 'Science'), ('FIC', 'Fiction'), ('NON', 'Non-Fiction')], max_length=5)),
            ],
        ),
    ]
